"
I represent a group of clubs that compete against each other.

For the Responsibility part: Three sentences about my main responsibilities - what I do, what I know.

For the Collaborators Part: State my main collaborators and one line about how I interact with them. 

Public API and Key Messages

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.

    Implementation Points
"
Class {
	#name : #League,
	#superclass : #Object,
	#instVars : [
		'clubs'
	],
	#category : #'Gymnastics-Core'
}
